[general]
import = ["~/.config/alacritty/themes/monokai.toml"]

[env]
# merges well with tmux
TERM = "xterm-256color"

[window]
# not very useful in a window manager
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.9 # just like wezterm?

[window.padding]
x = 2
y = 2

[font]
size = 13.0 # same as wezterm

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"

[colors]
draw_bold_text_with_bright_colors = true
